### ISSUE TITLE
Issue with module-info.java

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#188]
Hi, 
I've imported the project into Eclipse (2020-03) as Java project. After Mave update the only error is in module-info.java (interface expected). 
If possible please contact me on wojciech.wiza@gmail.com
Thanks!
Wojtek

**Comment by catalry** [comment]
Dear  wojciechwiza,
Maybe you could try to run mvn eclipse:eclipse then refresh the project?
Thank you for your interest.

**Comment by moniquewiza** [comment]
I did but even this does not allow to import the project as a web project, thus no way to create WAR from eclipse or to integrate with internal Tomcat.
We are using customized EUSurvey in our Agency and I'd be happy to provide our feedback, Is it possible to contact you by email?

**Comment by BRU-EUSurvey** [comment]
Hello,
I'm adding this to our list of points to address.

**Comment by clam2310** [comment]
I did not find a "module-info.java" file in the EUSurvey sources. Did you add one?

**Comment by moniquewiza** [comment]
I think it was a file created by Eclipse with unresolved imports. In fact we have switched now to IntelliJ IDEA so I think this was not an issue but rather a question how to import EUSurvey project into the IDE. In IDEA the project works ok so I propose to close this issue.
