### ISSUE TITLE
Confirmation of high-volume surveys in OSS version

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#241]
When a user creates new survey, he/she need to confirm that: "I confirm that we will inform the EUSurvey Team (digit-eusurvey-support@ec.europa.eu) if we expect a very high number of responses to this survey (50.000+), so that potential impact can be assessed and measures put in place to deal with the peak traffic."
In case of installations on own servers this confirmation make no sense.

I propose to remove this checkbox from the OSS version of EUSurvey (if oss=true) because it is not clear for users why they need to inform digit-eusurvey-support if the survey tool is not on COMM servers.

**Comment by BRU-EUSurvey** [comment]
Thank you.
Ticket 7261 created for this change request.

**Comment by BRU-EUSurvey** [comment]
Hello,
This is done.
The code has been changed (version 1.5.3).
Regards
