### ISSUE TITLE
Empty notifications

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#250]
Regularly I'm receiving empty notifications from the tool as below:
![image](https://user-images.githubusercontent.com/26763186/88164445-6db1c300-cc14-11ea-8934-f92467ce6f6e.png)

No further info in -info or -error log.

**Comment by catalry** [comment]
Dear @wojciechwiza , maybe it indicates javascript errors? Did you have anything in the F12 console ?

**Comment by moniquewiza** [comment]
Hi @catalry 
I'll check as soon as the reappear, thanks for the hint.
