### ISSUE TITLE
Uploaded files are not accessible for form managers - SOLVED

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#294]
I'm not sure if this is a bug or some misconfiguration. 
We have a survey where users may upload pdf files. In the result page uploaded files are visible, but as a link only to the administrator. For Form Managers (even if they have all privileges) they are presented as a plain text and they cannot download these submitted files.

If user is a Form Manager and have full rights to results they should be able to download associated files.

**Comment by BRU-EUSurvey** [comment]
Hi there,
Could you please add screenshots?
Many thanks

**Comment by moniquewiza** [comment]
Hi, here are admin view of results and form manager view of the same survey:
![admin-view](https://user-images.githubusercontent.com/26763186/116246637-75d1fc80-a76a-11eb-9cca-5207b5b2aac8.png)
![form-manager-view](https://user-images.githubusercontent.com/26763186/116246661-7c607400-a76a-11eb-89cc-1f3b170efcc2.png)

**Comment by BRU-EUSurvey** [comment]
Bug ticket 7198 created for this issue.
Planned for the next release 1.5.2.5.
