### ISSUE TITLE
Wrong country code (Critical!)

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#307]
Hi @catalry @clam2310 

The predefined list of EU countries has a wrong country code for Italy (IR instead of IT)

The problem is in a map in UtilsController line 43

**Comment by BRU-EUSurvey** [comment]
Hi there,
I have just checked, the EU member states display the correct code IT.
Perhaps, this has been fixed in the meantime?
Kind regards

**Comment by moniquewiza** [comment]
Hi, it was in the class indicated, if it is already corrected we can close this.

**Comment by BRU-EUSurvey** [comment]
Got it. Thank you

**Comment by BRU-EUSurvey** [comment]
Ticket 7273 created for this issue.

**Comment by BRU-EUSurvey** [comment]
Actually this issue has already been fixed in version 1.5.1 (ticket 6916).
