### ISSUE TITLE
Critical submission verification bug (CAPTCHA) - SOLVED

### ISSUE THREAD

**Issue by viessg** [EUSurvey/EUSURVEY#414]
**Describe the bug**
Critical bug what prevents submitting anything on eusurvey due incorrect human verification
https://ec.europa.eu/eusurvey
https://ec.europa.eu/eusurvey/home/support?language=en
tested in with Latvian and English languages

**To Reproduce**
1. using Google Chrome fill any form you find on eusurvey (bug is global and apparently applies to all forms)
2. when asked entering verification letters (verification field) - enter them as you see on screen 
3. receive verification error 

**Expected behavior**
You fill the form, enter correct verification code, shown with green letters on screen and it is accepted and data entered
 are submitted

**Screenshots**
![eusurvey](https://user-images.githubusercontent.com/79990395/109829504-44dfba80-7c46-11eb-81a8-1278f1ba16e7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Google chrome
 - Version 88.0.4324.190 (Official Build) (64-bit)

**Additional context**

**Comment by BRU-EUSurvey** [comment]
Hi there,
Thank you.
We plan to replace the current CAPTCHA by another one called 'EU CAPTCHA'.
This one will also integrate an audio CAPTCHA for visually-impaired readers.
Kind regards

**Comment by BRU-EUSurvey** [comment]
Ticket 3007 created to replace the current CAPTCHA.

**Comment by origabe** [comment]
the EUCaptcha service has been integrated in version 1.5.2.9
