### ISSUE TITLE
Improve the responsiveness on non-mobile devices? - Solved

### ISSUE THREAD

**Issue by cmarmo** [EUSurvey/EUSURVEY#42]
**Is your feature request related to a problem? Please describe.**
I have started to use EUSurvey via the [European Portal](https://ec.europa.eu/eusurvey) and I really appreciate the number of available options of customization for survey questions and management. I'm happy to see that the survey rendering is responsive depending on the device used to answer to the survey.
However, it seems to me that on PC screens the output page width is fixed to `1300px`, making window resizing a bit awkward.

**Describe the solution you'd like**
I'm not familiar with Java, so I'm not sure this could be a good solution, because I'm not comfortable in testing it. Anyway, it seems to me that [this line](https://github.com/EUSurvey/EUSURVEY/blob/973d94f09420e85bf132ebe798ee8f7c7d29ee9e/src/main/webapp/WEB-INF/views/runner/runnercontent.jsp#L10), could probably be updated with `width: 100%`.
Then maybe some small details on `right-area` and `left-area` classes should be updated too?

Thanks for listening and thanks for your code.

**Comment by BRU-EUSurvey** [comment]
Issue 7292 logged.
What do you call the output page?
Is it the page where the survey is displayed (form runner) or the confirmation page that is displayed right after submission (click on the 'submit' button)?
Maybe the Results screen?

**Comment by cmarmo** [comment]
Dear @BRU-EUSurvey, thanks for coming back to me.
I have deleted the survey results and the survey itself since then. To be honest I can't recall the details of my issue.
I think that the result screen was the issue... 
Feel free to close this one if it is not reproducible.
