### ISSUE TITLE
Bar plot for slider

### ISSUE THREAD

**Issue by bertvandepoel** [EUSurvey/EUSURVEY#433]
**Is your feature request related to a problem? Please describe.**
When viewing responses on a survey and using the % option, I was surprised to find I got a nice bar plot for a dropdown selection question but not for the 5 point Likert scale questions.

**Describe the solution you'd like**
It would be nice to get a bar plot of some kind to see the distribution across the numeric scores of a slider question.

**Describe alternatives you've considered**
There are other plots to visualize it, of course. The main idea is that it would at least be visualized somehow. Currently I can't even see an average or get the frequency of each number, it's treated the same as an open question.

**Comment by BRU-EUSurvey** [comment]
Hi There,
Many thanks for the feedback.
Indeed, we plan to add more graphs and options to the Stat '%' screen.
Actually, we have just done it for a new module currently under-dev.
Ideally, each question element should have at least one graph type to display the results.
In parallel, we are working to integrate our tool with a data analytical tool (ex-Kibana) but this will take some time.
Kind regards

**Comment by BRU-EUSurvey** [comment]
Hello,

This is now possible to have a bar chart for Slider question in the % stats screen.

Example below:

![image](https://github.com/EUSurvey/EUSURVEY/assets/83012143/d150dc05-f767-44e2-9e9a-cb9100c84f90)

![image](https://github.com/EUSurvey/EUSURVEY/assets/83012143/ae5dc7c3-38b6-4be0-949e-a085922f15c7)

Regards

**Comment by bertvandepoel** [comment]
Awesome, thank you! :D
