### ISSUE TITLE
UX: gray icons suggest unavailability of the feature

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#459]
In the survey Editor a set of icons on the right used of hiding/displaying panes (Navigation/Toolbox/Properties) turns grey when the pane is closed (see picture)
![image](https://user-images.githubusercontent.com/26763186/120205465-465f5580-c22a-11eb-9bd1-097a95355b5b.png)
For a common user the grey colour suggests that the element is unavailable. 

I propose to change the UX of the icons so the colour would not confuse users like:
![image](https://user-images.githubusercontent.com/26763186/120205791-a6ee9280-c22a-11eb-8ab0-0d70b96c1037.png)
when property pane is closed (to open it), and
![image](https://user-images.githubusercontent.com/26763186/120205865-bff74380-c22a-11eb-9888-a022bbe76918.png)
when the property pane is open (to hide it)

**Comment by LMA-EUSurvey** [comment]
Dear wojciechwiza,

Thank you for your suggestion.

I will open an internal ticket for the business analyst and developer.

Please note that if accepted, this improvement might take a while to be implemented in the tool.

Best regards

EUSurvey Support
European Commission

**Comment by LMA-EUSurvey** [comment]
ESURVEY-7360

**Comment by BRU-EUSurvey** [comment]
If we do this, we have to change a lot of icons and we don't have the no-icons. They would need to be re-created or taken from a new source. Also, I understand the point made but this do not seem to be unclear for most users.
