### ISSUE TITLE
File size limit for File Upload control - SOLVED

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#460]
Currently, when a File Upload control is used, the help text says that the max file size is 1MB

![image](https://user-images.githubusercontent.com/26763186/120206113-11073780-c22b-11eb-9f5c-4036c4f2474b.png)

It would be great to have this customizable allowing participants to send bigger files (e.g. set up in the application properties file). This is quite common for dedicated public consultations with business - their positions are lengthy and text field is to short.

**Comment by DefaultDeveloperName** [comment]
> It would be great to have this customizable allowing participants to send bigger files 

+1

**Comment by LMA-EUSurvey** [comment]
Dear  wojciechwiza,

Thank you for your message.

In fact, it is not possible to customize file size. 

We EUSurvey Support can modify that but you need to provide more information, such as:
1- How many participants do you expect
2- Why do you need particpants to send bigger files

Do not hesitate to come back in case of need. 

Best regards
Luísa Martins
EUSurvey Support
European Commission

**Comment by moniquewiza** [comment]
Dear @LMA-EUSurvey 

Yes, I know it is impossible now, but it would be a desired feature. In contemporary IT environment files are very often bigger than 1MB.
1. I'm not sure if the number of participants is an important factor as OSS version is typically installed on own premises. So this is a problem of the system administrator to secure appropriate amount of disk space for all participants (typically we have 100+ participants). It would be also a role of an admin to define max limits for file sizes.
2. The free text control is limited to max 5k characters. This is not enough for some our questionnaires where we asking to provide a justification on very technically and legally complex issues. Very often instead of using limited size text field we are allowing participants to upload the file. As mentioned before, 1MB is very low limit as attached e.g. legislation analysis can have even 10-15MB PDF files, not mention other file types (Word, Excel, etc.)

Therefore the administrator of the OSS server should have a possibility to change this maximum value according to expected contribution file sizes and available file system.

Best regards
Monique

**Comment by LMA-EUSurvey** [comment]
Dear Monique,

I was advise that you have a schedule meeting with my Business Analyst colleague.

This issue will be address in the meeting and will possibly be included in the requirements document we are writing for ACER.

Do not hesitate to come back in case of need.

Best regards
Luísa Martins
EUSurvey Support
European Commission

**Comment by origabe** [comment]
Dear,
It is now possible for the form manager to choose the limit of the file upload question type, between:
1, 2, 5, 10 MB

**Comment by Pat551119** [comment]
Dear Origabe, 
It is great news.
But how or where can I change or select the size other than 1 MB? I could not find it.
Thanks. 
Best regards, 
Pat

**Comment by origabe** [comment]
Dear Pat551119,
When you add a 'File upload' type of question and select it in the editor. 
You can find in the 'Element Properties' pane, an entry: 'Maximum File size' where you can select a size between: 1,2,5,10 MB.
See screenshot attached
![FileUpload_Limit](https://user-images.githubusercontent.com/33053863/216294000-c2d089aa-2764-429a-82fb-48c08d524f31.PNG)

**Comment by Pat551119** [comment]
Thank you origabe for your promte answer.

But on my screen there is no such a dropbdown-option. (Please see the screenshot below).
Something goes wrong. Do you know how to correct this error?

Thank you in advance! 
Best regards, Pat
![grafik](https://user-images.githubusercontent.com/124205181/216315147-ae264af3-9d6c-49c5-afa0-b94ee8528b5b.png)

**Comment by yujidevelle1** [comment]
Hi there, it looks like I have the same issue at @Pat551119. Can't find the dropdown to change file upload limit to 10MB. Anyone can help?
