### ISSUE TITLE
Rating control can be separated  - SOLVED

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#461]
The Rating control containing more than one rating element permits to 'detach' the element from the container:
before:
![image](https://user-images.githubusercontent.com/26763186/120206553-a0ace600-c22b-11eb-9984-eebe399d94f3.png)
after:
![image](https://user-images.githubusercontent.com/26763186/120206621-b91d0080-c22b-11eb-8e30-c7d6a8604376.png)
just by 'drag and drag'. 

It 'self-corrects' when a user click 'Save' button but before the separated element cannot be moved back to the container and cannot be deleted. If a user has no practice with this behaviour it is difficult to cope with the situation.

To reproduce:
1. create a Rating control
2. click and drag on one of the rating elements
3. the rating elements 'disconnects' from the container

This disconnection behaviour should probably be forbidden by blocking a drag and drop

**Comment by LMA-EUSurvey** [comment]
ESURVEY-7368

**Comment by LMA-EUSurvey** [comment]
Thank you for your message.

I can indeed reproduce the issue.

I have created an internal ticket in order to fix this issue as soon as possible. 

Best regards

EUSurvey Support
European Commission

**Comment by LMA-EUSurvey** [comment]
Dear Monique,

This issue has been solved and implemented in the latest deployment of EUSURVEY.

Do not hesitate to come back in case of need.

Best regards

EUSURVEY Support

**Comment by moniquewiza** [comment]
Thank you for the update. Are you planning a new version roll out or it is just updated with minor version release?
Best
Monique

**Comment by LMA-EUSurvey** [comment]
Hello Monique,

Yes, we have deployed a new version of EUSURVEY. You can find the latest release note here: https://circabc.europa.eu/ui/group/599f39d2-e0cc-4765-bfdc-c9917c931509/library/c755a28d-8a61-4bce-819b-da4bed773b9b/details 

Best regards

EUSURVEY Support
