### ISSUE TITLE
Max characters property in free text question control takes prefill form data - SOLVED

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#465]
When editing a free text question, in the properties window 'Max characters' input is automatically pre-filled with the name of a user (if auto-complete option is on in the browser).

**To Reproduce**
1. Click on any free text control
2. Open properties window
3. The Max characters input field is filled in with user name

**Expected behavior**
The field should remain empty. Probably there is coincidence in the name (id) of the max characters field and user name control?

![image](https://user-images.githubusercontent.com/26763186/126516539-c24b8cbc-514c-4b5b-bf94-0d34c4161d9b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1909
 - Browser Chrome 91.0.4472.164

This require to have form auto-complete turned in

**Comment by feketga** [comment]
Dear Monique!

Please note that ESURVEY-7405 ticket was created for your issue. You will be informed about any update on it.

Thank you!

**Comment by feketga** [comment]
Dear Monique!

I would like to inform you that your issue was solved and max character field should not contain any prefilled data anymore. Please test it on your side and let me know if you need further assistance on it.

Thank you!
