### ISSUE TITLE
Wrong value of "type" attribute of MatrixQuestion elements in XML export - SOLVED

### ISSUE THREAD

**Issue by gpeche** [EUSurvey/EUSURVEY#472]
When exporting to XML either using the web UI or the REST API, the attribute "type" of MatrixQuestion elements contains the value "Single Choice Matrix Question: " (note trailing colon and space) instead of the documented "Single Choice Matrix Question".

A reading of https://github.com/EUSurvey/EUSURVEY/blob/20d1121327f7578b62147e80843f502629a6e98c/src/main/java/com/ec/survey/tools/export/XmlExportCreator.java#L132 in this repository suggests that multiple choice questions present the same misbehaviour.

Regards

**Comment by LMA-EUSurvey** [comment]
Dear gpeche, 

Thank you for your message.

I will have a look at your request and get back to you as soon as possible.

Best regards
EUSurvey Support
European Commission

**Comment by LMA-EUSurvey** [comment]
An internal ticket was created in order to solve this issue as soon as possible: ESURVEY-7487

**Comment by LMA-EUSurvey** [comment]
Dear gpeche,

This improvement has been implemented on the last version of EUSURVEY. 

Best regards
EUSurvey Support
European Commission
