### ISSUE TITLE
eusurvey.war not found - SOLVED

### ISSUE THREAD

**Issue by DamianoP** [EUSurvey/EUSURVEY#480]
I'm building a docker container with your code for the HPC lab of the University of Perugia, but it fails becouse the ./dist/eusurvey.war is not included in the repository

How can i solve the problem ?
Thank you
Best regards

**Comment by LMA-EUSurvey** [comment]
Dear Damiano,
Thank you for your contact.
Could you please send us more details about what you are trying to do? ./dist/eusurvey.war is not necessarily needed and we do not use docker at all. 

Best regards
EUSURVEY Support

**Comment by DamianoP** [comment]
I would like to install the application on a linux server to try it
I've seen that in your repository there is the folder with the Docker configuration and I thought it was to install it automatically.
https://github.com/EUSurvey/EUSURVEY/tree/master/docker

**Comment by LMA-EUSurvey** [comment]
Dear Damiano,

We have created an internal ticket in order to investigate and fix this issue. 

I will get back to you as soon as possible.
Best regards
EUSURVEY Support

**Comment by LMA-EUSurvey** [comment]
[ESURVEY-7645]

**Comment by LMA-EUSurvey** [comment]
Dear Damiano,

Please find below the guidelines:

Here the recipe to use the docker configuration:

Solution to make it work right now:

Adapt configuration in src/main/config/ossdocker/spring.properties
Build via mvn clean package -U -Denvironment=ossdocker
Copy target/eusurvey.war to docker/server/dist/eusurvey.war
mkdir -p ~/eusurveytemp
docker-compose build
docker-compose up -d

EUSurvey is then accessible on localhost:8888/eusurvey. Adapt docker-compose.yaml as required. Please note that no volume bind for MySQL is currently defined, so you will start with a fresh database anytime you restart the MySQL container.

Hope this helps and do not hesitate to come back in case of need.

Best regards
EUSurvey Support
