### ISSUE TITLE
Online version doesn't show submitted surveys

### ISSUE THREAD

**Issue by fgianneschi** [EUSurvey/EUSURVEY#481]
Hello, I'm using the online version of EUSurvey at https://ec.europa.eu/eusurvey/

I've noticed that the submissions (real or test ones, doesn't matter) are not shown immediately on the results page. Nor they are counted in the dashboard. They show after a while, usually a (random?) amount of minutes that sometimes is quite high.

Even logging out and logging in again doesn't solve the problem.

**Comment by LMA-EUSurvey** [comment]
Dear fgianneschi, 

Thank you for your contact.

A new database has been introduced which shall improve EUSurvey's performance when querying your survey's results. However, this can lead to some delays until the latest data is displayed on the Results page of your survey. This delay should not be more than 12 hours.

If the displayed data is older than 12 hours, please contact EUSURVEY support.

In case any, please send me the survey link and I will have a look.

Best regards
EUSurvey Support

**Comment by fgianneschi** [comment]
Thank for the clarification.
However I think that such delay complicates the test phase, if the survey editor can't see the results immediately.

**Comment by BRU-EUSurvey** [comment]
Thank you, your feedback will be taken into consideration for future upgrade.
Reporting database might be decommissioned as several users provided the same feedback.
