### ISSUE TITLE
Typo with parentheses in JS function call 

### ISSUE THREAD

**Issue by piotrkiraga** [EUSurvey/EUSURVEY#498]
https://github.com/EUSurvey/EUSURVEY/blob/8d09db06726bac22c5433b7bcb35ba1b6c3d4f12/src/main/webapp/resources/js/runner.js#L1253

Should be:
submitToChangeLanguageOrView(true, mode);

Instead of:
submitToChangeLanguageOrView(true), mode;

In:
runner.js#changeLanguageSelectOption(mode)

**Comment by BRU-EUSurvey** [comment]
Bug ticket created: 7981

Thank you for the feedback !

**Comment by BRU-EUSurvey** [comment]
Fixed as part of Sprint 26.

**Comment by BRU-EUSurvey** [comment]
Version 43cbc4f24ea472ca6267aa3fa77db55c5ae0d7a3 (15/05/2023 11:26)
Not on PROD yet.

**Comment by BRU-EUSurvey** [comment]
FYI, the fix has been released.

**Comment by BRU-EUSurvey** [comment]
Released in March 2024.
