### ISSUE TITLE
Some users cannot see the file upload size limit changer dropdown menu

### ISSUE THREAD

**Issue by yujidevelle1** [EUSurvey/EUSURVEY#507]
Dear Pat551119,
When you add a 'File upload' type of question and select it in the editor. 
You can find in the 'Element Properties' pane, an entry: 'Maximum File size' where you can select a size between: 1,2,5,10 MB.
See screenshot attached
![FileUpload_Limit](https://user-images.githubusercontent.com/33053863/216294000-c2d089aa-2764-429a-82fb-48c08d524f31.PNG)

_Originally posted by @origabe in https://github.com/EUSurvey/EUSURVEY/issues/460#issuecomment-1413461246_

**Comment by yujidevelle1** [comment]
In my (and all of my colleagues') EUSurvey tools, we cannot find this dropdown that you are referring to. Maybe it is related to the fact that we are not EU employees but third-party employees?
![image_480](https://user-images.githubusercontent.com/125651978/219614012-599a8048-da21-458f-a8c9-050b47249171.png)

**Comment by BRU-EUSurvey** [comment]
Dear User,
Thank you for contacting us and apologies for the delay.
May I ask you if you use the OSS version (i.e. your own instance) or our PRODUCTION environment (https://ec.europa.eu/eusurvey/home/welcome) ?
Regards

**Comment by origabe** [comment]
> In my (and all of my colleagues') EUSurvey tools, we cannot find this dropdown that you are referring to. Maybe it is related to the fact that we are not EU employees but third-party employees? ![image_480](https://user-images.githubusercontent.com/125651978/219614012-599a8048-da21-458f-a8c9-050b47249171.png)

Indeed, my mistake not to have mentioned it, it's actually a limit only available to the administrator of the service.
If you are using an instance of the open source version you should be able to modify this limit, but if you are using the EUSurvey European Comission service (https://ec.europa.eu/eusurvey), you need to contact the support team via : https://ec.europa.eu/eusurvey/home/support 
to request an increase of this limit, mentioning then the business case, the alias of the survey, the questions for which the limit should be increased and the target audience of the survey.

**Comment by origabe** [comment]
If you need to raise the limit please contact the support team in using the form mentioned.
