### ISSUE TITLE
SandraRubi

### ISSUE THREAD

**Issue by PaulinaCarrilloRuiz09** [EUSurvey/EUSURVEY#521]
Hola [hola**Describe](url
![archive_action](https://github.com/EUSurvey/EUSURVEY/assets/154306280/b711b1fc-455f-4882-893c-c6809934e8bc)
#) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by origabe** [comment]
A good template to report an issue.
Thank you @PaulinaCarrilloRuiz09
