### ISSUE TITLE
Solved - Cannot find list of question types in your documentation

### ISSUE THREAD

**Issue by Chris-ECE** [EUSurvey/EUSURVEY#531]
Hello,

I have been trying to find out what question types are supported by EUsurvey, but I cannot find this in your documentation: [https://bo-survey.berec.europa.eu/eusurvey/home/helpauthors](https://bo-survey.berec.europa.eu/eusurvey/home/helpauthors)

I would be very grateful if an _**exhaustive**_ list of question types can be provided, either in the GitHub readme, or on the above-mentioned webpage. (Or if this is already documented somewhere, to signpost that documentation more clearly from the readme file.)

Appreciate your help!

**Comment by origabe** [comment]
Hello,

Please note that the official instance of EUSurvey is located here: https://ec.europa.eu/eusurvey/
Regarding the types of questions available, you will find here: https://ec.europa.eu/eusurvey/runner/TutorialEUSurvey a survey containing most of the question types currently offered by EUSurvey.
There is no comprehensive list of the question types available in the Help pages.
KR
