### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by rugk** [EUSurvey/EUSURVEY#540]
The activity really seems to decrease since this was initially developed and I see many issues not being answered. See https://github.com/EUSurvey/EUSURVEY/graphs/contributors

You can [archive this repository](https://docs.github.com/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository/archiving-repositories), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

**Comment by jobenjada** [comment]
yay mention Formbricks please :D it's AGPLv3 and we improve it every day!

**Comment by origabe** [comment]
Dear,
The EUSurvey project is still maintained and active.
